# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateSandboxRequest(BaseModel):
    """
    CreateSandboxRequest
    """ # noqa: E501
    name: Annotated[str, Field(strict=True)] = Field(description="DNS-1123 subdomain format", json_schema_extra={"examples": ["vm-01"]})
    image: Optional[StrictStr] = Field(default=None, description="Image name in `name:ver` or `name` format. If omitted, defaults to the latest active `code` image.", json_schema_extra={"examples": ["code"]})
    cpu: Optional[Annotated[int, Field(le=8, strict=True, ge=1)]] = Field(default=None, description="Number of vCPUs", json_schema_extra={"examples": [2]})
    mem: Optional[Annotated[int, Field(le=16384, strict=True, ge=1024)]] = Field(default=None, description="Memory in MiB", json_schema_extra={"examples": [2048]})
    org_id: Optional[StrictStr] = Field(default=None, description="Organization that owns the sandbox. When omitted, derived from the authenticated API key (the key's org). When provided, must match the key's organization or the request is rejected.", alias="orgId", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    user_id: Optional[StrictStr] = Field(default=None, description="User attributed as the sandbox creator. When omitted, derived from the API key (typically the key creator). When provided, must be an owner or member of the resolved org or the request is rejected.", alias="userId", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    sync: Optional[StrictBool] = Field(default=True, description="If true (default), creation blocks until the agent responds (fast readiness check, ~2s timeout)", json_schema_extra={"examples": [True]})
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, description="Environment variables to set on the sandbox", alias="envVars", json_schema_extra={"examples": [{"DEBUG": "true", "LOG_LEVEL": "info"}]})
    auto_sleep: Optional[StrictBool] = Field(default=None, description="If true, the sandbox is auto-snapshotted after idle and wakes on the next request", alias="autoSleep", json_schema_extra={"examples": [True]})
    region: Optional[StrictStr] = Field(default=None, description="Target region for the sandbox", json_schema_extra={"examples": ["eu"]})
    publish_ports: Optional[List[Annotated[int, Field(le=65535, strict=True, ge=1)]]] = Field(default=None, description="Sandbox ports to expose through the public gateway. Each entry is published as a separate public URL once the VM is running.", alias="publishPorts", json_schema_extra={"examples": [[8080, 3000]]})
    labels: Optional[Dict[str, Annotated[str, Field(strict=True, max_length=20)]]] = Field(default=None, description="Key-value labels attached at creation. Immutable after the sandbox is created. Max 5 labels; keys and values may each contain up to 20 characters. Keys match `^[a-z0-9]([-a-z0-9_]*[a-z0-9])?$`; neither keys nor values may contain `,` or `=`.", json_schema_extra={"examples": [{"env": "prod", "team": "backend"}]})
    __properties: ClassVar[List[str]] = ["name", "image", "cpu", "mem", "orgId", "userId", "sync", "envVars", "autoSleep", "region", "publishPorts", "labels"]

    @field_validator('name', mode="before")
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSandboxRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSandboxRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "image": obj.get("image"),
            "cpu": obj.get("cpu"),
            "mem": obj.get("mem"),
            "orgId": obj.get("orgId"),
            "userId": obj.get("userId"),
            "sync": obj.get("sync") if obj.get("sync") is not None else True,
            "envVars": obj.get("envVars"),
            "autoSleep": obj.get("autoSleep"),
            "region": obj.get("region"),
            "publishPorts": obj.get("publishPorts"),
            "labels": obj.get("labels")
        })
        return _obj


