# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExecRequest(BaseModel):
    """
    ExecRequest
    """ # noqa: E501
    command: StrictStr = Field(json_schema_extra={"examples": ["ls -la /root"]})
    args: Optional[List[StrictStr]] = Field(default=None, json_schema_extra={"examples": [["-la", "/root"]]})
    timeout: Optional[StrictInt] = Field(default=30, description="Timeout in seconds", json_schema_extra={"examples": [30]})
    env: Optional[Dict[str, StrictStr]] = Field(default=None, json_schema_extra={"examples": [{"PATH": "/usr/bin:/bin"}]})
    cwd: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["/root"]})
    __properties: ClassVar[List[str]] = ["command", "args", "timeout", "env", "cwd"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command": obj.get("command"),
            "args": obj.get("args"),
            "timeout": obj.get("timeout") if obj.get("timeout") is not None else 30,
            "env": obj.get("env"),
            "cwd": obj.get("cwd")
        })
        return _obj


