# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GeneratedAPIKeyResponse(BaseModel):
    """
    GeneratedAPIKeyResponse
    """ # noqa: E501
    plain_key: Optional[StrictStr] = Field(default=None, description="Only returned once at generation time", alias="plainKey", json_schema_extra={"examples": ["hf_1234567890abcdef"]})
    key_id: Optional[StrictStr] = Field(default=None, alias="keyId", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    key_name: Optional[StrictStr] = Field(default=None, alias="keyName", json_schema_extra={"examples": ["CI/CD Key"]})
    org_id: Optional[StrictStr] = Field(default=None, alias="orgId", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    expires_in: Optional[StrictStr] = Field(default=None, alias="expiresIn", json_schema_extra={"examples": ["Key expires in 1 year"]})
    __properties: ClassVar[List[str]] = ["plainKey", "keyId", "keyName", "orgId", "createdAt", "expiresIn"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneratedAPIKeyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneratedAPIKeyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plainKey": obj.get("plainKey"),
            "keyId": obj.get("keyId"),
            "keyName": obj.get("keyName"),
            "orgId": obj.get("orgId"),
            "createdAt": obj.get("createdAt"),
            "expiresIn": obj.get("expiresIn")
        })
        return _obj


