# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from voidrun.api_client.models.get_current_user200_response_orgs_inner import GetCurrentUser200ResponseOrgsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetCurrentUser200Response(BaseModel):
    """
    GetCurrentUser200Response
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Admin User"]})
    email: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["admin@example.com"]})
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl", json_schema_extra={"examples": ["https://example.com/avatar.png"]})
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    orgs: Optional[List[GetCurrentUser200ResponseOrgsInner]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "email", "imageUrl", "createdAt", "orgs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetCurrentUser200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in orgs (list)
        _items = []
        if self.orgs:
            for _item_orgs in self.orgs:
                if _item_orgs:
                    _items.append(_item_orgs.to_dict())
            _dict['orgs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetCurrentUser200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "imageUrl": obj.get("imageUrl"),
            "createdAt": obj.get("createdAt"),
            "orgs": [GetCurrentUser200ResponseOrgsInner.from_dict(_item) for _item in obj["orgs"]] if obj.get("orgs") is not None else None
        })
        return _obj


