# coding: utf-8

"""
    Hyper Fleet Native API

    Hyper Fleet Native API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/register` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RestoreSandboxRequest(BaseModel):
    """
    RestoreSandboxRequest
    """ # noqa: E501
    new_id: StrictStr
    snapshot_path: StrictStr
    new_ip: Optional[StrictStr] = None
    cold: Optional[StrictBool] = Field(default=False, description="Start in stopped state")
    cpu: Optional[Annotated[int, Field(le=8, strict=True, ge=1)]] = None
    mem: Optional[Annotated[int, Field(le=16384, strict=True, ge=1024)]] = None
    org_id: StrictStr = Field(alias="orgId")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    __properties: ClassVar[List[str]] = ["new_id", "snapshot_path", "new_ip", "cold", "cpu", "mem", "orgId", "userId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestoreSandboxRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestoreSandboxRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "new_id": obj.get("new_id"),
            "snapshot_path": obj.get("snapshot_path"),
            "new_ip": obj.get("new_ip"),
            "cold": obj.get("cold") if obj.get("cold") is not None else False,
            "cpu": obj.get("cpu"),
            "mem": obj.get("mem"),
            "orgId": obj.get("orgId"),
            "userId": obj.get("userId")
        })
        return _obj


