# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Sandbox(BaseModel):
    """
    Sandbox
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["vm-01"]})
    image: Optional[StrictStr] = Field(default=None, description="Resolved image in `name:ver` format", json_schema_extra={"examples": ["code:1.0.42"]})
    cpu: Optional[StrictInt] = Field(default=None, description="Number of vCPUs allocated", json_schema_extra={"examples": [2]})
    mem: Optional[StrictInt] = Field(default=None, description="Memory in MiB", json_schema_extra={"examples": [2048]})
    disk_mb: Optional[StrictInt] = Field(default=None, description="Disk size in MiB", alias="diskMB", json_schema_extra={"examples": [10240]})
    status: Optional[StrictStr] = Field(default=None, description="Lifecycle state. Terminal states `killed` and `deleted` may still appear in list responses for historical or cleanup rows.", json_schema_extra={"examples": ["running"]})
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, description="User ID who created the sandbox", alias="createdBy", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    org_id: Optional[StrictStr] = Field(default=None, description="Organization ID the sandbox belongs to", alias="orgId", json_schema_extra={"examples": ["65ae1234567890abcdef1234"]})
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, description="Environment variables set on the sandbox (optional, only present if configured)", alias="envVars", json_schema_extra={"examples": [{"DEBUG": "true", "LOG_LEVEL": "info"}]})
    auto_sleep: Optional[StrictBool] = Field(default=None, description="Indicates if auto-sleep is enabled", alias="autoSleep", json_schema_extra={"examples": [True]})
    region: Optional[StrictStr] = Field(default=None, description="Region where the sandbox is hosted", json_schema_extra={"examples": ["us-east-1"]})
    node_id: Optional[StrictStr] = Field(default=None, description="Voidrun host that created this sandbox", alias="nodeId", json_schema_extra={"examples": ["host-fra-01"]})
    publish_ports: Optional[List[Annotated[int, Field(le=65535, strict=True, ge=1)]]] = Field(default=None, description="Ports exposed through the public gateway. Empty when the sandbox is not publicly reachable.", alias="publishPorts", json_schema_extra={"examples": [[8080]]})
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="Key-value labels attached at creation (immutable). Only present if set. See `GET /sandboxes` `labels` query parameter for filtering.", json_schema_extra={"examples": [{"env": "prod", "team": "backend"}]})
    __properties: ClassVar[List[str]] = ["id", "name", "image", "cpu", "mem", "diskMB", "status", "createdAt", "createdBy", "orgId", "envVars", "autoSleep", "region", "nodeId", "publishPorts", "labels"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['running', 'snapshotted', 'error', 'killed', 'deleted']):
            raise ValueError("must be one of enum values ('running', 'snapshotted', 'error', 'killed', 'deleted')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sandbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sandbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "image": obj.get("image"),
            "cpu": obj.get("cpu"),
            "mem": obj.get("mem"),
            "diskMB": obj.get("diskMB"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "orgId": obj.get("orgId"),
            "envVars": obj.get("envVars"),
            "autoSleep": obj.get("autoSleep"),
            "region": obj.get("region"),
            "nodeId": obj.get("nodeId"),
            "publishPorts": obj.get("publishPorts"),
            "labels": obj.get("labels")
        })
        return _obj


