# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Sandbox(BaseModel):
    """
    Sandbox
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    image: Optional[StrictStr] = Field(default=None, description="Image name or ID used to create the sandbox")
    cpu: Optional[StrictInt] = Field(default=None, description="Number of vCPUs allocated")
    mem: Optional[StrictInt] = Field(default=None, description="Memory in MiB")
    disk_mb: Optional[StrictInt] = Field(default=None, description="Disk size in MiB", alias="diskMB")
    status: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, description="User ID who created the sandbox", alias="createdBy")
    org_id: Optional[StrictStr] = Field(default=None, description="Organization ID the sandbox belongs to", alias="orgId")
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, description="Environment variables set on the sandbox (optional, only present if configured)", alias="envVars")
    disable_pause: Optional[StrictBool] = Field(default=None, description="Indicates if auto-pause is disabled", alias="disablePause")
    region: Optional[StrictStr] = Field(default=None, description="Region where the sandbox is hosted")
    ref_id: Optional[StrictStr] = Field(default=None, description="External reference ID", alias="refId")
    __properties: ClassVar[List[str]] = ["id", "name", "image", "cpu", "mem", "diskMB", "status", "createdAt", "createdBy", "orgId", "envVars", "disablePause", "region", "refId"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['running', 'stopped', 'paused', 'error']):
            raise ValueError("must be one of enum values ('running', 'stopped', 'paused', 'error')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sandbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sandbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "image": obj.get("image"),
            "cpu": obj.get("cpu"),
            "mem": obj.get("mem"),
            "diskMB": obj.get("diskMB"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "orgId": obj.get("orgId"),
            "envVars": obj.get("envVars"),
            "disablePause": obj.get("disablePause"),
            "region": obj.get("region"),
            "refId": obj.get("refId")
        })
        return _obj


