# coding: utf-8

"""
    VoidRun API

    VoidRun API provides comprehensive management of virtual machines (sandboxes),  file system operations, execution environments, and organizational resources.  All endpoints except `/api/version` require the `X-API-Key` header for authentication. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionExecRequest(BaseModel):
    """
    SessionExecRequest
    """ # noqa: E501
    action: StrictStr = Field(json_schema_extra={"examples": ["create"]})
    session_id: Optional[StrictStr] = Field(default=None, description="Required for all actions except create", alias="sessionId", json_schema_extra={"examples": ["sess-1a2b3c4d5e6f7788"]})
    shell: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["/bin/bash"]})
    command: Optional[StrictStr] = Field(default=None, description="Required when action is `exec`", json_schema_extra={"examples": ["ls -la"]})
    input: Optional[StrictStr] = Field(default=None, description="Input text when action is `input`", json_schema_extra={"examples": ["y\n"]})
    cols: Optional[Annotated[int, Field(le=500, strict=True, ge=1)]] = Field(default=None, description="Required when action is `resize`", json_schema_extra={"examples": [120]})
    rows: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = Field(default=None, description="Required when action is `resize`", json_schema_extra={"examples": [40]})
    __properties: ClassVar[List[str]] = ["action", "sessionId", "shell", "command", "input", "cols", "rows"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['create', 'exec', 'input', 'resize', 'close']):
            raise ValueError("must be one of enum values ('create', 'exec', 'input', 'resize', 'close')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionExecRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionExecRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "sessionId": obj.get("sessionId"),
            "shell": obj.get("shell"),
            "command": obj.get("command"),
            "input": obj.get("input"),
            "cols": obj.get("cols"),
            "rows": obj.get("rows")
        })
        return _obj


